### PR TITLE
Feature/visualiser/panning

### PR DESCRIPTION
**Pull request by jedwed**
Panning on Visualiser Canvas implemented through pointer events.
Mainly following this tutorial: https://css-tricks.com/creating-a-panning-effect-for-svg/

### CODE REVIEW

**Comment by lukefisklennon** [comment]
Looks good overall, just wondering if it's intended that the screen pans at a faster rate than your mouse movement?

**Comment by dqna64** [comment]
Pretty good so far 🤩 I'm seeing a bug where the zooming is not centered on the mouse, what's causing this and how to fix?

https://github.com/csesoc/structs.sh/assets/76837291/57d30af4-e715-4b36-9e94-9c68a0e94b9f

**Review by dqna64 — APPROVED** [review]
LGTM after the above bug is sorted :DD

**Comment by jedwed** [comment]
> Looks good overall, just wondering if it's intended that the screen pans at a faster rate than your mouse movement?

I believe it should be at the same rate since the pan is the offset of the mouse position. I'll merge this in for now and if there are issues we can resolve them.

**Pull request merged**
